theme: jekyll-theme-midnight
title: Gostat
url: "https://gostat501.github.io"

include:
  - _pages
  
# Apply default layout to pages in _pages/
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: default